import React,{useState,useEffect}from'react';import api from'../services/api';import Modal from'../components/Modal';import DetailPanel from'../components/DetailPanel';
export default function DatabasesPage(){const[items,setItems]=useState([]),[sel,setSel]=useState(null),[modal,setModal]=useState(false),[editing,setEditing]=useState(false),[form,setForm]=useState({name:'',host:'',port:5432,db_name:'',db_type:'PostgreSQL',status:'healthy'});
useEffect(()=>{load()},[]);const load=()=>api.getDatabases().then(setItems).catch(console.error);
const submit=async e=>{e.preventDefault();if(editing)await api.updateDatabase(sel.id,form);else await api.createDatabase(form);setModal(false);setEditing(false);load()};
const edit=()=>{setForm({name:sel.name,host:sel.host,port:sel.port,db_name:sel.db_name,db_type:sel.db_type,status:sel.status});setEditing(true);setModal(true);setSel(null)};
const del=async()=>{if(window.confirm('Delete?')){await api.deleteDatabase(sel.id);setSel(null);load()}};
const st=s=>({padding:'4px 10px',borderRadius:12,fontSize:11,fontWeight:'bold',background:s==='healthy'?'#2ecc7120':s==='warning'?'#f39c1220':'#e9456020',color:s==='healthy'?'#2ecc71':s==='warning'?'#f39c12':'#e94560'});
const inp={width:'100%',padding:'10px 14px',background:'#1a1a2e',border:'1px solid #0f3460',borderRadius:8,color:'#e0e0e0',fontSize:14,marginBottom:12,outline:'none'};
return(<div style={{padding:30}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:24}}><h1 style={{fontSize:24,color:'#e0e0e0'}}>Monitored Databases</h1><button style={{padding:'10px 20px',background:'#e94560',color:'#fff',border:'none',borderRadius:8,cursor:'pointer',fontWeight:'bold'}} onClick={()=>{setEditing(false);setForm({name:'',host:'',port:5432,db_name:'',db_type:'PostgreSQL',status:'healthy'});setModal(true)}}>+ Add Database</button></div>
<table style={{width:'100%',borderCollapse:'collapse',background:'#16213e',borderRadius:12,overflow:'hidden'}}><thead><tr>{['Name','Host','Type','Status','Size','Queries','Slow'].map(h=><th key={h} style={{padding:'12px 16px',textAlign:'left',background:'#0f3460',color:'#a0a0b0',fontSize:12,textTransform:'uppercase'}}>{h}</th>)}</tr></thead><tbody>{items.map(d=><tr key={d.id} style={{cursor:'pointer'}} onClick={()=>setSel(d)} onMouseEnter={e=>e.currentTarget.style.background='#0f346020'} onMouseLeave={e=>e.currentTarget.style.background='transparent'}><td style={{padding:'12px 16px',borderBottom:'1px solid #0f346030',fontSize:14}}><strong>{d.name}</strong></td><td style={{padding:'12px 16px',borderBottom:'1px solid #0f346030',fontSize:13}}>{d.host}:{d.port}</td><td style={{padding:'12px 16px',borderBottom:'1px solid #0f346030',fontSize:13}}><code style={{background:'#1a1a2e',padding:'2px 6px',borderRadius:4}}>{d.db_type}</code></td><td style={{padding:'12px 16px',borderBottom:'1px solid #0f346030'}}><span style={st(d.status)}>{d.status}</span></td><td style={{padding:'12px 16px',borderBottom:'1px solid #0f346030',fontSize:13}}>{(d.size_mb/1024).toFixed(1)} GB</td><td style={{padding:'12px 16px',borderBottom:'1px solid #0f346030',fontSize:13}}>{Number(d.total_queries).toLocaleString()}</td><td style={{padding:'12px 16px',borderBottom:'1px solid #0f346030',fontSize:13,color:'#e94560'}}>{d.slow_queries}</td></tr>)}</tbody></table>
<Modal isOpen={modal} onClose={()=>setModal(false)} title={editing?'Edit Database':'Add Database'}><form onSubmit={submit}>{[['Name','name'],['Host','host'],['Port','port'],['Database Name','db_name'],['Type','db_type']].map(([l,k])=><div key={k}><label style={{color:'#a0a0b0',fontSize:12}}>{l}</label><input style={inp} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} required={k==='name'}/></div>)}<button style={{width:'100%',padding:12,background:'#e94560',color:'#fff',border:'none',borderRadius:8,cursor:'pointer',fontWeight:'bold'}} type="submit">{editing?'Update':'Add'}</button></form></Modal>
<DetailPanel isOpen={!!sel} onClose={()=>setSel(null)} title="Database Details">{sel&&<>{[['Name',sel.name],['Host',`${sel.host}:${sel.port}`],['Database',sel.db_name],['Type',sel.db_type],['Status',sel.status],['Size',`${(sel.size_mb/1024).toFixed(1)} GB`],['Total Queries',Number(sel.total_queries).toLocaleString()],['Slow Queries',sel.slow_queries],['Uptime',`${sel.uptime_hours}h`]].map(([l,v])=><div key={l} style={{marginBottom:16}}><div style={{color:'#a0a0b0',fontSize:12}}>{l}</div><div style={{color:'#e0e0e0',fontSize:14}}>{v}</div></div>)}<div style={{display:'flex',gap:10,marginTop:20}}><button style={{flex:1,padding:10,background:'#0f3460',color:'#e0e0e0',border:'none',borderRadius:8,cursor:'pointer',fontWeight:'bold'}} onClick={edit}>✏️ Edit</button><button style={{flex:1,padding:10,background:'#e94560',color:'#fff',border:'none',borderRadius:8,cursor:'pointer',fontWeight:'bold'}} onClick={del}>🗑️ Delete</button></div></>}</DetailPanel></div>)}
